create table FIRE
(
ID int auto_increment comment 'Primary Key, auto increment',
X int not null comment 'X coordinate of the fire hotspot in the positioning canvas',
Y int not null comment 'Y coordinate of the fire hostspot in the positioning canvas',
MIN_HEAT int not null comment 'The minumum heat of the fire',
MAX_HEAT int not null comment 'The maximum heat of the fire',
MIN_SMOKE int not null comment 'The minumum smoke of the fire',
MAX_SMOKE int not null comment 'The maximum smoke of the fire',
SMOKE_EVAPORATION_RATE double(5,4) not null comment 'The smoke evaporation rate',
EVAPORATION_RATE double(5,3) not null comment 'The rate that fire naturally got extinguished',
DIFFUSION_RATE double(5,3) not null comment 'The rate that diffuse the fire',
FIRE_SPREAD_PROBABILITY double(5,3) not null comment 'The probability of being spreading fire to neighbor''s cells',
STARTING_TIME int not null comment 'The time that starts the fire',
MINIMUM_DIFFUSE_PROBABILITY double(5,3) not null comment 'For diffusion - minimum probability of fire diffusion',
MAXIMUM_DIFFUSE_PROBABILITY double(5,3) not null comment 'For diffusion - maximmum probability of fire diffusion',
MINIMUM_EVAPORATION_PROBABILITY double(5,3) not null comment 'For evaporation - minimum probability of fire evaporation',
MAXIMUM_EVAPORATION_PROBABILITY double(5,3) not null comment 'For evaporation - maximum probability of fire evaporation',
INCREMENT_PROBABILITY double(5,3) not null comment 'The probability of fire being increased, (1-this) gives the probability of fire being decreased',
FUSABLE_SMOKE_AMOUNT int not null comment 'The smoke amount that needs to exists prior to fuse the fire',
FUSABLE_PROBABILITY double(5,3) not null comment 'The probability of fire being fused given it has enough smoke',
SMOKE_AMOUNT int not null comment 'The amount of smoke generated by the fire',
ENABLE boolean not null comment 'Specifies whether the fire is paticipated in the simulation with enable status, enable or disable: 0 - false and 1 - true',
ACTIVE boolean default true not null comment 'Specifies whether the fire is subjected to participate in the simulation: 0 - false and 1 - true',
ORIGINATOR varchar(10) not null comment 'The origination of the information: PERSON, SYSTEM',
SEVERITY varchar(10) comment 'The severity of the fire: SEVERE, NORMAL, MILD',
BUILDING_ID int comment 'Building (Burning) id. ref: Building',
COALITION_ID int comment 'Coalition id. ref: Coalition',
TIME datetime default current_timestamp on update current_timestamp comment 'Time stamp of the record created or updated',
constraint FIRE_PK primary key (ID),
constraint FIRE_ORIG_CK check (ORIGINATOR in ('PERSON','SYSTEM')),
constraint FIRE_BUILD_FK foreign key (BUILDING_ID) references BUILDING(ID),
constraint FIRE_COAL_FK foreign key (COALITION_ID) references COALITION(ID)
)
comment 'Store the fire information',
ENGINE=INNODB;

insert into FIRE (X, Y, MIN_HEAT, MAX_HEAT, MIN_SMOKE, MAX_SMOKE, 
  SMOKE_EVAPORATION_RATE, EVAPORATION_RATE, DIFFUSION_RATE, STARTING_TIME, 
  FIRE_SPREAD_PROBABILITY, MINIMUM_DIFFUSE_PROBABILITY, MAXIMUM_DIFFUSE_PROBABILITY,
  MINIMUM_EVAPORATION_PROBABILITY, MAXIMUM_EVAPORATION_PROBABILITY, INCREMENT_PROBABILITY,
  FUSABLE_SMOKE_AMOUNT, FUSABLE_PROBABILITY, SMOKE_AMOUNT, ENABLE, ORIGINATOR)
values 
(70, 35, 6000, 10000, 450, 100000, 
  0.01, 0.993, 1.0, 5, 
  0.06, 0.3, 0.4,
  0.1, 0.2, 0.51,
  10000, 0.3, 900, 1, 'PERSON')
;

INSERT INTO `fire` (`ID`,`X`,`Y`,`MIN_HEAT`,`MAX_HEAT`,`MIN_SMOKE`,`MAX_SMOKE`,`SMOKE_EVAPORATION_RATE`,`EVAPORATION_RATE`,`DIFFUSION_RATE`,`FIRE_SPREAD_PROBABILITY`,`STARTING_TIME`,`MINIMUM_DIFFUSE_PROBABILITY`,`MAXIMUM_DIFFUSE_PROBABILITY`,`MINIMUM_EVAPORATION_PROBABILITY`,`MAXIMUM_EVAPORATION_PROBABILITY`,`INCREMENT_PROBABILITY`,`FUSABLE_SMOKE_AMOUNT`,`FUSABLE_PROBABILITY`,`SMOKE_AMOUNT`,`ENABLE`,`ACTIVE`,`ORIGINATOR`,`BUILDING_ID`,`COALITION_ID`,`TIME`,`SEVERITY`) VALUES (2,63,36,12000,16000,1500,100000,0.0010,0.771,1.000,0.180,0,0.500,0.600,0.010,0.020,0.710,10000,0.700,900,1,1,'PERSON',8,NULL,'2018-06-17 18:29:29','SEVERE');
INSERT INTO `fire` (`ID`,`X`,`Y`,`MIN_HEAT`,`MAX_HEAT`,`MIN_SMOKE`,`MAX_SMOKE`,`SMOKE_EVAPORATION_RATE`,`EVAPORATION_RATE`,`DIFFUSION_RATE`,`FIRE_SPREAD_PROBABILITY`,`STARTING_TIME`,`MINIMUM_DIFFUSE_PROBABILITY`,`MAXIMUM_DIFFUSE_PROBABILITY`,`MINIMUM_EVAPORATION_PROBABILITY`,`MAXIMUM_EVAPORATION_PROBABILITY`,`INCREMENT_PROBABILITY`,`FUSABLE_SMOKE_AMOUNT`,`FUSABLE_PROBABILITY`,`SMOKE_AMOUNT`,`ENABLE`,`ACTIVE`,`ORIGINATOR`,`BUILDING_ID`,`COALITION_ID`,`TIME`,`SEVERITY`) VALUES (3,72,46,6000,10000,450,100000,0.0100,0.993,1.000,0.060,0,0.300,0.400,0.100,0.200,0.510,10000,0.300,900,1,1,'PERSON',8,NULL,'2018-06-17 18:29:45','MILD');
INSERT INTO `fire` (`ID`,`X`,`Y`,`MIN_HEAT`,`MAX_HEAT`,`MIN_SMOKE`,`MAX_SMOKE`,`SMOKE_EVAPORATION_RATE`,`EVAPORATION_RATE`,`DIFFUSION_RATE`,`FIRE_SPREAD_PROBABILITY`,`STARTING_TIME`,`MINIMUM_DIFFUSE_PROBABILITY`,`MAXIMUM_DIFFUSE_PROBABILITY`,`MINIMUM_EVAPORATION_PROBABILITY`,`MAXIMUM_EVAPORATION_PROBABILITY`,`INCREMENT_PROBABILITY`,`FUSABLE_SMOKE_AMOUNT`,`FUSABLE_PROBABILITY`,`SMOKE_AMOUNT`,`ENABLE`,`ACTIVE`,`ORIGINATOR`,`BUILDING_ID`,`COALITION_ID`,`TIME`,`SEVERITY`) VALUES (4,67,43,9000,13000,1000,100000,0.0050,0.882,1.000,0.120,0,0.400,0.500,0.040,0.060,0.610,10000,0.500,900,1,1,'PERSON',8,NULL,'2018-06-17 18:29:53','NORMAL');

commit;